#!/usr/bin/env python3
"""Generate .mscz files with pre-placed fretboard diagrams from voicings.json.

Each generated file contains a single measure with a whole note and a
fretboard diagram showing the complete voicing (dots, markers, barres).
Open in MuseScore and copy-paste the diagram into your working score.

Usage:
    python generate_mscz.py --voicing c7-shell-137-e-str-7 --root F
    python generate_mscz.py --voicing c7-shell-137-e-str-7  # defaults to C
    python generate_mscz.py --all --root Bb --output diagrams/
"""

import argparse
import json
import os
import sys
import zipfile
from pathlib import Path

SEMITONE_MAP = {
    "C": 0, "B#": 0, "C#": 1, "Db": 1, "D": 2, "D#": 3, "Eb": 3,
    "E": 4, "Fb": 4, "F": 5, "E#": 5, "F#": 6, "Gb": 6, "G": 7,
    "G#": 8, "Ab": 8, "A": 9, "A#": 10, "Bb": 10, "B": 11, "Cb": 11,
}

# MIDI pitch for middle C (C4)
MIDI_C4 = 60


def semitone_offset(source_root: str, target_root: str) -> int:
    src = SEMITONE_MAP.get(source_root)
    tgt = SEMITONE_MAP.get(target_root)
    if src is None or tgt is None:
        raise ValueError(f"Unknown root: {source_root} or {target_root}")
    return (tgt - src) % 12


def generate_fret_diagram_xml(voicing: dict, target_root: str = "C") -> str:
    """Generate the <FretDiagram> XML element with full dot/marker data."""
    offset = semitone_offset(voicing["root"], target_root)
    transposed_fret = voicing["fret_number"] + offset
    num_strings = voicing.get("strings", 6)
    num_frets = voicing.get("visible_frets", 4)

    # Build per-string data (MS4 uses 0-based, 0=highest pitched)
    string_data: dict[int, dict] = {}

    for dot in voicing.get("dots", []):
        ms_str = num_strings - dot["string"]
        string_data.setdefault(ms_str, {})["dot"] = dot["fret"]

    for mute_str in voicing.get("mutes", []):
        ms_str = num_strings - mute_str
        string_data.setdefault(ms_str, {})["marker"] = "cross"

    for open_str in voicing.get("open", []):
        ms_str = num_strings - open_str
        string_data.setdefault(ms_str, {})["marker"] = "circle"

    lines = [
        "          <FretDiagram>",
        f"            <fretOffset>{transposed_fret - 1}</fretOffset>",
        f"            <frets>{num_frets}</frets>",
        f"            <strings>{num_strings}</strings>",
        "            <fretDiagram>",
    ]

    for ms_str in sorted(string_data.keys()):
        data = string_data[ms_str]
        lines.append(f'              <string no="{ms_str}">')
        if "marker" in data:
            lines.append(f"                <marker>{data['marker']}</marker>")
        if "dot" in data:
            lines.append(f'                <dot fret="{data["dot"]}">normal</dot>')
        lines.append("              </string>")

    lines.append("            </fretDiagram>")
    lines.append("          </FretDiagram>")
    return "\n".join(lines)


def generate_mscx(voicing: dict, target_root: str = "C") -> str:
    """Generate a complete .mscx XML score with one measure containing
    a whole note and a fretboard diagram."""
    offset = semitone_offset(voicing["root"], target_root)
    midi_pitch = MIDI_C4 + offset  # root note pitch
    name = voicing["name"].replace("C", target_root, 1) if target_root != "C" else voicing["name"]
    fret_xml = generate_fret_diagram_xml(voicing, target_root)

    # Guitar string tuning (standard 6-string or 7-string Van Eps)
    if voicing.get("strings", 6) == 7:
        string_data = """          <StringData>
            <frets>24</frets>
            <string>33</string>
            <string>40</string>
            <string>45</string>
            <string>50</string>
            <string>55</string>
            <string>59</string>
            <string>64</string>
            </StringData>"""
    else:
        string_data = """          <StringData>
            <frets>24</frets>
            <string>40</string>
            <string>45</string>
            <string>50</string>
            <string>55</string>
            <string>59</string>
            <string>64</string>
            </StringData>"""

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<museScore version="4.60">
  <programVersion>4.6.5</programVersion>
  <Score>
    <Division>480</Division>
    <showInvisible>1</showInvisible>
    <showUnprintable>1</showUnprintable>
    <showFrames>1</showFrames>
    <showMargins>0</showMargins>
    <metaTag name="workTitle">{name}</metaTag>
    <metaTag name="arranger">Generated by Chord Library Plugin</metaTag>
    <Part id="1">
      <Staff>
        <StaffType group="pitched">
          <name>stdNormal</name>
          </StaffType>
        </Staff>
      <trackName>Guitar</trackName>
      <Instrument id="electric-guitar">
        <longName>Electric Guitar</longName>
        <shortName>E.Guit.</shortName>
        <trackName>Electric Guitar</trackName>
        <transposeDiatonic>-7</transposeDiatonic>
        <transposeChromatic>-12</transposeChromatic>
{string_data}
        <Channel name="open">
          <program value="27"/>
          </Channel>
        </Instrument>
      </Part>
    <Staff id="1">
      <VBox>
        <height>10</height>
        <Text>
          <style>title</style>
          <text>{name}</text>
          </Text>
        </VBox>
      <Measure>
        <voice>
          <TimeSig>
            <sigN>4</sigN>
            <sigD>4</sigD>
            </TimeSig>
          <Chord>
            <durationType>whole</durationType>
{fret_xml}
            <Note>
              <pitch>{midi_pitch}</pitch>
              <tpc>{14 + offset if offset < 6 else 14 + offset - 12}</tpc>
              </Note>
            </Chord>
          </voice>
        </Measure>
      </Staff>
    </Score>
  </museScore>
"""


def generate_mscz(voicing: dict, target_root: str, output_path: Path):
    """Generate a .mscz file (zip containing .mscx)."""
    mscx_content = generate_mscx(voicing, target_root)
    score_name = output_path.stem

    with zipfile.ZipFile(output_path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(f"{score_name}.mscx", mscx_content)
        zf.writestr("META-INF/container.xml",
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            '<container><rootfiles>'
            f'<rootfile full-path="{score_name}.mscx"/>'
            '</rootfiles></container>\n')


def main():
    parser = argparse.ArgumentParser(
        description="Generate .mscz files with fretboard diagrams from voicings.json"
    )
    parser.add_argument("--voicing", help="Voicing ID from voicings.json")
    parser.add_argument("--root", default="C", help="Target root note (default: C)")
    parser.add_argument("--all", action="store_true", help="Generate for all voicings")
    parser.add_argument("--output", "-o", help="Output directory (for --all) or file path")
    parser.add_argument(
        "--data",
        default=str(Path(__file__).parent.parent / "data" / "voicings.json"),
        help="Path to voicings.json",
    )
    args = parser.parse_args()

    with open(args.data) as f:
        data = json.load(f)

    voicings = {v["id"]: v for v in data["voicings"]}

    if args.all:
        out_dir = Path(args.output) if args.output else Path("diagrams")
        out_dir.mkdir(parents=True, exist_ok=True)
        for vid, v in voicings.items():
            out_file = out_dir / f"{vid}_{args.root}.mscz"
            generate_mscz(v, args.root, out_file)
            print(f"  {out_file}")
        print(f"\nGenerated {len(voicings)} .mscz files in {out_dir}/")
    elif args.voicing:
        if args.voicing not in voicings:
            print(f"Error: voicing '{args.voicing}' not found.", file=sys.stderr)
            print(f"Available: {', '.join(sorted(voicings.keys()))}", file=sys.stderr)
            sys.exit(1)
        v = voicings[args.voicing]
        if args.output:
            out_file = Path(args.output)
        else:
            out_file = Path(f"{args.voicing}_{args.root}.mscz")
        generate_mscz(v, args.root, out_file)
        print(f"Generated: {out_file}")
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
