#!/usr/bin/env python3
"""Generate the flat manifest file the bash queue runner consumes.

Reads every *.toml under pipelines/master-distillation/configs/, emits a
tab-separated record per book:

    <slug>\t<needs_ocr:0|1>\t<pdf-path>

Books WITHOUT source.host = cyberpower are skipped (they're either
already-promoted historical configs or out-of-scope local-only).

Output path defaults to $HOME/jazz-pipeline/manifest.tsv on the cyberpower
side; override with --output. The manifest must be regenerated whenever
the configs change (when you merge a queue-rewrite PR like #335).

Usage (on cyberpower, after git pull):
    python3 manifest_from_configs.py
"""

from __future__ import annotations

import argparse
import os
import sys
import tomllib
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--configs",
        default=str(Path(__file__).resolve().parents[1] / "configs"),
        help="Directory containing config *.toml files",
    )
    parser.add_argument(
        "--output",
        default=os.path.expanduser("~/jazz-pipeline/manifest.tsv"),
        help="Where to write the flat manifest",
    )
    parser.add_argument(
        "--require-host",
        default="cyberpower",
        help="Only include configs whose source.host matches this; pass empty to include all",
    )
    args = parser.parse_args()

    configs_dir = Path(args.configs)
    if not configs_dir.is_dir():
        print(f"configs dir not found: {configs_dir}", file=sys.stderr)
        return 2

    records: list[tuple[str, str, str]] = []
    skipped = 0
    for path in sorted(configs_dir.glob("*.toml")):
        try:
            data = tomllib.loads(path.read_text())
        except tomllib.TOMLDecodeError as exc:
            print(f"WARN: skip {path.name} (parse error: {exc})", file=sys.stderr)
            continue

        source = data.get("source", {})
        host = source.get("host", "")
        pdf = source.get("pdf", "")
        needs_ocr = source.get("needs_ocr", False)

        if args.require_host and host != args.require_host:
            skipped += 1
            continue
        if not pdf:
            print(f"WARN: skip {path.name} (no source.pdf)", file=sys.stderr)
            continue

        slug = path.stem
        ocr_flag = "1" if needs_ocr else "0"
        records.append((slug, ocr_flag, pdf))

    output_path = Path(os.path.expanduser(args.output))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w") as f:
        f.write("# slug\tneeds_ocr\tpdf-path\n")
        f.write("# regenerated by manifest_from_configs.py\n")
        for slug, ocr_flag, pdf in records:
            f.write(f"{slug}\t{ocr_flag}\t{pdf}\n")

    print(
        f"wrote {len(records)} records to {output_path}; "
        f"skipped {skipped} configs (host != {args.require_host or '(any)'})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
